// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA7giasip4Pxbt3qaqo57wlWXWKkGrhgI',
    appId: '1:650853821789:web:3e5b65a37a1373bdbeccb4',
    messagingSenderId: '650853821789',
    projectId: 'unisqlproject',
    authDomain: 'unisqlproject.firebaseapp.com',
    databaseURL: 'https://unisqlproject-default-rtdb.firebaseio.com',
    storageBucket: 'unisqlproject.appspot.com',
    measurementId: 'G-PD6RPJ7BS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfXeZR51GDP1fLnFRbvht4Zz3qVQEgFJc',
    appId: '1:650853821789:android:565cae2a1aea8c50beccb4',
    messagingSenderId: '650853821789',
    projectId: 'unisqlproject',
    databaseURL: 'https://unisqlproject-default-rtdb.firebaseio.com',
    storageBucket: 'unisqlproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfkn9GpXkdh573vtD5fuOgPL0xTBiJVPw',
    appId: '1:650853821789:ios:e01212e8fbd434e6beccb4',
    messagingSenderId: '650853821789',
    projectId: 'unisqlproject',
    databaseURL: 'https://unisqlproject-default-rtdb.firebaseio.com',
    storageBucket: 'unisqlproject.appspot.com',
    iosBundleId: 'com.example.unisqProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfkn9GpXkdh573vtD5fuOgPL0xTBiJVPw',
    appId: '1:650853821789:ios:fb92444dce00e897beccb4',
    messagingSenderId: '650853821789',
    projectId: 'unisqlproject',
    databaseURL: 'https://unisqlproject-default-rtdb.firebaseio.com',
    storageBucket: 'unisqlproject.appspot.com',
    iosBundleId: 'com.example.unisqProject.RunnerTests',
  );
}
